// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_TheilSen
arma::vec rcpp_TheilSen(const arma::vec X, const arma::vec Y, const bool verbose, const arma::uword medind, const arma::uword medind2);
RcppExport SEXP _robslopes_rcpp_TheilSen(SEXP XSEXP, SEXP YSEXP, SEXP verboseSEXP, SEXP medindSEXP, SEXP medind2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type medind(medindSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type medind2(medind2SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_TheilSen(X, Y, verbose, medind, medind2));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_RepeatedMedian
arma::vec rcpp_RepeatedMedian(const arma::vec X, const arma::vec Y, const bool verbose, const arma::uword medind, const arma::uvec medind2);
RcppExport SEXP _robslopes_rcpp_RepeatedMedian(SEXP XSEXP, SEXP YSEXP, SEXP verboseSEXP, SEXP medindSEXP, SEXP medind2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type medind(medindSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type medind2(medind2SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_RepeatedMedian(X, Y, verbose, medind, medind2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_robslopes_rcpp_TheilSen", (DL_FUNC) &_robslopes_rcpp_TheilSen, 5},
    {"_robslopes_rcpp_RepeatedMedian", (DL_FUNC) &_robslopes_rcpp_RepeatedMedian, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_robslopes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
