# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_TheilSen <- function(X, Y, verbose, medind, medind2) {
    .Call(`_robslopes_rcpp_TheilSen`, X, Y, verbose, medind, medind2)
}

rcpp_RepeatedMedian <- function(X, Y, verbose, medind, medind2) {
    .Call(`_robslopes_rcpp_RepeatedMedian`, X, Y, verbose, medind, medind2)
}

