# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countIndividualInversions <- function(y) {
    .Call(`_robslopes_countIndividualInversions`, y)
}

rcpp_PassingBablok <- function(X, Y, verbose, medind0, medind1) {
    .Call(`_robslopes_rcpp_PassingBablok`, X, Y, verbose, medind0, medind1)
}

rcpp_TheilSen <- function(X, Y, verbose, medind0, medind1) {
    .Call(`_robslopes_rcpp_TheilSen`, X, Y, verbose, medind0, medind1)
}

rcpp_countIAs <- function(X, Y, theta_lo, theta_hi) {
    .Call(`_robslopes_rcpp_countIAs`, X, Y, theta_lo, theta_hi)
}

rcpp_RepeatedMedian <- function(X, Y, verbose, medind0, medind1, medind2) {
    .Call(`_robslopes_rcpp_RepeatedMedian`, X, Y, verbose, medind0, medind1, medind2)
}

